# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v ./...

    - name: Test
      运行： go test -v ./...name: IPTV-Go

on:

  push:

    branches: ["main"]

    paths:

      - '**.go'    

  pull_request:

    branches: ["main"]

    paths:

      - '**.go'

jobs:

  linux_amd64_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Cross Compile

        run: |

          cd ./Golang

          GOOS=linux GOARCH=amd64 go build -o allinone_linux_amd64

      - name: Upload Cross Compile Artifacts

        uses: actions/upload-artifact@v3

        with:

          name: allinone_linux_amd64

          path: Golang/allinone_linux_amd64

  linux_arm64_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Cross Compile

        run: |

          cd ./Golang

          GOOS=linux GOARCH=arm64 go build -o allinone_linux_arm64

      - name: Upload Cross Compile Artifacts

        uses: actions/upload-artifact@v3

        with:

          name: allinone_linux_arm64

          path: Golang/allinone_linux_arm64

  darwin_amd64_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Cross Compile

        run: |

          cd ./Golang

          GOOS=darwin GOARCH=amd64 go build -o allinone_darwin_amd64

      - name: Upload Cross Compile Artifacts

        uses: actions/upload-artifact@v3

        with:

          name: allinone_darwin_amd64

          path: Golang/allinone_darwin_amd64

  darwin_arm64_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Cross Compile

        run: |

          cd ./Golang

          GOOS=darwin GOARCH=arm64 go build -o allinone_darwin_arm64

      - name: Upload Cross Compile Artifacts

        uses: actions/upload-artifact@v3

        with:

          name: allinone_darwin_arm64

          path: Golang/allinone_darwin_arm64

  

  windows_amd64_build:

    runs-on: ubuntu-latest

    steps:

      - uses: actions/checkout@v3

      - name: Cross Compile

        run: |

          cd ./Golang

          GOOS=windows GOARCH=amd64 go build -o allinone_windows_amd64.exe

      - name: Upload Cross Compile Artifacts

        uses: actions/upload-artifact@v3

        with:

          name: allinone_windows_amd64

          path: Golang/allinone_windows_amd64.exe
